// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTcnRqsgsk00n2VONRQVNRpM8c1b_y3o',
    appId: '1:703715306814:web:05e7823cdbfa28279b506f',
    messagingSenderId: '703715306814',
    projectId: 'chat-app-d4636',
    authDomain: 'chat-app-d4636.firebaseapp.com',
    storageBucket: 'chat-app-d4636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldS_zrvttNI8Z8PLDPW9TPrdL4OWEt1I',
    appId: '1:703715306814:android:765365f47868d0869b506f',
    messagingSenderId: '703715306814',
    projectId: 'chat-app-d4636',
    storageBucket: 'chat-app-d4636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVN-kETJ_nGxJjrjDFzCsyocQCes3COYE',
    appId: '1:703715306814:ios:2e84061b6cbaf7539b506f',
    messagingSenderId: '703715306814',
    projectId: 'chat-app-d4636',
    storageBucket: 'chat-app-d4636.appspot.com',
    iosClientId: '703715306814-1cfpjtr94c7cpij9b5qm1o74omtn5sno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
